# class RootException(Exception):
#     pass


# class AuthError(RootException):
#     pass
